source/course_interviews/urls.py
from django.conf.urls import url

from .views import (index, get_students, get_emails, get_all_emails, confirm_interview,
                    choose_interview, confirm_slot, get_interview_slots, confirm_student_interview)

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^api/get-students/(?P<course>[-\w]+)/$', get_students, name="get_students"),
    url(r'^api/get-emails/$', get_emails, name="get_emails"),
    url(r'^api/get-all-emails/$', get_all_emails, name="get_all_emails"),
    url(r'^api/get-interview-slots/$', get_interview_slots, name="get_interview_slots"),
    url(r'^confirm-interview/(?P<token>[-\w]+)/$', confirm_interview, name="confirm_interview"),
    url(r'^choose-interview/(?P<token>[-\w]+)/$', choose_interview, name="choose_interview"),
    url(r'^confirm-slot/$', confirm_slot, name="confirm_slot"),
    url(r'^confirm-student-interview/$', confirm_student_interview, name="confirm_student_interview"),
]

source/interview_communicator/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('course_interviews.urls', namespace='course_interviews'))
]

source/course_interviews/models.py
# -*- coding: utf-8 -*-
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django_extensions.db.fields import UUIDField
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
import uuid


class SiteUserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The given email address must be set')

        email = SiteUserManager.normalize_email(email)
        user = self.model(email=email,
                          is_staff=False, is_active=True, **extra_fields)

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        u = self.create_user(email, password, **extra_fields)
        u.is_staff = True
        u.is_active = True
        u.is_superuser = True
        u.save(using=self._db)
        return u


class Teacher(AbstractBaseUser, PermissionsMixin):

    objects = SiteUserManager()

    email = models.EmailField(unique=True, blank=False)
    skype = models.CharField(
        default=None,
        max_length=50,
        help_text='Enter the skype of the teacher!')
    first_name = models.CharField(default="", max_length=50)
    last_name = models.CharField(default="", max_length=50)

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'skype']

    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def get_short_name(self):
        return self.first_name

    def __str__(self):
        return self.get_full_name()


class Student(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    skype = models.CharField(default=None, max_length=1100)
    phone_number = PhoneNumberField(blank=True)
    applied_course = models.CharField(null=True, blank=True, max_length=1100)
    first_task = models.URLField(null=True, blank=True)
    second_task = models.URLField(null=True, blank=True)
    third_task = models.URLField(null=True, blank=True)
    studies_at = models.CharField(blank=True, null=True, max_length=1100)
    works_at = models.CharField(null=True, blank=True, max_length=1100)

    # possible_rating is number between 1 and 10 to be selected in the integer field
    possible_ratings = [(i, i) for i in range(11)]
    code_skills_rating = models.IntegerField(
        default=0,
        choices=possible_ratings,
        help_text='Оценка върху уменията на кандидата да пише'
        ' код и знанията му върху базови алгоритми')
    code_design_rating = models.IntegerField(
        default=0,
        choices=possible_ratings,
        help_text='Оценка върху уменията на кандидата да "съставя'
        ' програми" и да разбива нещата по парчета + базово OOP')
    fit_attitude_rating = models.IntegerField(
        default=0,
        choices=possible_ratings,
        help_text='Оценка на интервюиращия в зависимост от'
        ' усета му за човека (става ли за курса)')
    teacher_comment = models.TextField(
        null=True,
        blank=True,
        help_text='Коментар на интервюиращия за цялостното представяне на кандидата')
    has_interview_date = models.BooleanField(default=False)
    has_received_email = models.BooleanField(default=False)
    has_received_new_courses_email = models.BooleanField(default=False)
    has_confirmed_interview = models.BooleanField(default=False)
    has_been_interviewed = models.BooleanField(default=False)
    is_accepted = models.BooleanField(default=False)
    uuid = UUIDField(version=4, unique=True, default=uuid.uuid4)

    def __str__(self):
        return self.name


class InterviewerFreeTime(models.Model):
    teacher = models.ForeignKey(Teacher)
    date = models.DateField(blank=False, null=True)
    start_time = models.TimeField(blank=False, null=True)
    end_time = models.TimeField(blank=False, null=True)
    buffer_time = models.BooleanField(default=False)

    # method for checking if the slots for the specific interviewer free time
    # are already generated. Method is called by /helpers/generate_interview_slots.py
    def has_generated_slots(self):
        return self.interviewslot_set.exists()

    def __str__(self):
        return str(self.date) + " - from " + str(self.start_time) + " to " + str(self.end_time)


class InterviewSlot(models.Model):
    teacher_time_slot = models.ForeignKey(InterviewerFreeTime)
    student = models.OneToOneField(Student, null=True, blank=True)
    start_time = models.TimeField(blank=False, null=True)
    buffer_slot = models.BooleanField(default=False)

source/course_interviews/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import Student
from .apis import *


def index(request):
    return render(request, "index.html", locals())


def confirm_interview(request, token):
    student = get_object_or_404(Student, uuid=token)
    teacher_skype = student.interviewslot.teacher_time_slot.teacher.skype

    return render(request, "confirm_interview.html", locals())


def choose_interview(request, token):
    student = get_object_or_404(Student, uuid=token)

    if student.has_confirmed_interview:
        raise Http404("Student already has an interview date")

    return render(request, "choose_interview.html", locals())

source/course_interviews/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HackBulgaria Interviews</title>

    <link rel="stylesheet" href="{% static 'bower_components/bootstrap/dist/css/bootstrap.min.css' %}">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'bower_components/font-awesome/css/font-awesome.min.css' %}">
  </head>

  <body>
  <div id="page-wrap">

    <div id="header">

      <nav class="navbar navbar-default">
        <div class="navbar-header">
          <a id="logo" class="navbar-brand" href="https://hackbulgaria.com/">
            <img alt="Brand" src="{% static 'images/hackbulgaria_logo.png' %}">
          </a>
        </div>
      </nav>

    </div>

    <div id="content">
    {% block 'page-content' %}

    {% endblock %}
    </div>

    <div id="footer">

      <div id="socials">
        <a href="https://github.com/HackBulgaria/" target="_blank">
          <i class="fa fa-github fa-3x"></i>
        </a>

        <a href="https://www.facebook.com/HackBulgaria" target="_blank">
          <i class="fa fa-facebook-square fa-3x"></i>
        </a>

        <a href="https://www.youtube.com/user/HackBulgaria/feed" target="_blank">
          <i class="fa fa-youtube-play fa-3x"></i>
        </a>

        <a href="https://twitter.com/hackbulgaria" target="_blank">
          <i class="fa fa-twitter fa-3x"></i>
        </a>
      </div>

      HackBulgaria. All rights reserved.
    </div>

  </div>
  
  </body>
  <script type="text/javascript" src="{% static 'bower_components/jquery/dist/jquery.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'bower_components/handlebars/handlebars.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/choose_new_interview.js' %}"></script>
  {% block 'scripts' %}

  {% endblock %}
</html>

source/course_interviews/templates/choose_interview.html
{% extends 'base.html' %}

{% block 'page-content' %}
{% autoescape off %}
<div class="container">
  <div class="row">
    <div class="container-fluid">

      <div class="choose-interview-container col-md-8 col-md-offset-2">
        <h2>Choose your interview date and hour</h2>
        <div class="table-responsive">
          <table id="interview-slots-table" class="table table-hover">
            <thead>
              <tr>
                <th>Date</th>
                <th>Starting time</th>
                <th></th>
              </tr>
            </thead>
            <tbody>

            </tbody>
          </table>
        </div>

      </div>

    </div>
  </div>
</div>
{% endautoescape %}

<!-- Interview Already Taken Modal  -->
<div  id="interview-taken" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-body">
        <h4>
          <span id="errors">
            
          </span>
        </h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<!-- Selected interview confirmation Modal-->
<div id="confirm-selected-interview" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Confirm the selected interview slot</h4>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to select this interview slot? If you confirm it, you will <b>NOT</b> be able to select another one.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default confirm-chosen-interview" data-dismiss="modal">Confirm</button>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<!-- Handlebars template-->
<script id="interview-slots-template" type="text/x-handlebars-template">
  {% verbatim %}
    <tr>
      <td>{{ date }}</td>
      <td>{{ time }}</td>
      <td><button type="button" data-slotid="{{ slot_id }}" class="btn btn-primary choose-interview" data-toggle="modal" data-target="#confirm-selected-interview">Select Interview</button></td>
    </tr>
  {% endverbatim %}
</script>

{% endblock %}
{% block 'scripts' %}
<script type="text/javascript">
  (function(){
    $('.confirm-chosen-interview').click(function(e){
      $('#confirm-selected-interview').modal('hide');

      $.ajax({
        type: "POST",
        url: "{% url 'course_interviews:confirm_slot' %}",
        data: {
          'slot_id': window.slotId,
          'student_uuid': '{{ token }}', 
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },

        success: function(data) {
          var token = '{{token}}'
          $(location).attr("href", "{% url 'course_interviews:confirm_interview' token %} ")
        },

        error: function(data){
          $('#errors').text(data.responseText)
          $('#interview-taken').modal('show');
          $('#interview-taken').on('hidden.bs.modal', function () {
              location.reload();
          })
        }

      });
    });
  })();
</script>
{% endblock %}

source/course_interviews/templates/confirm_interview.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block 'page-content' %}
{% autoescape off %}
<div class="container">

  <div class="image-container">
    <img src="{% static 'images/competition.gif' %}">
  </div>

  <div class="confirm-text-container">
    <h1>Your interview is confirmed!</h1>
    <h3>Your tech interview for the {{ student.applied_course }} course is scheduled for {{ student.interviewslot.teacher_time_slot.date }} at {{ student.interviewslot.start_time }}</h3>
    <h3>The skype of your interviewer is {{ teacher_skype }}</h3>
    <h3>If you are unable to attend your interview, please contact us at hackbulgaria@gmail.com </h3>
  </div>

</div>
{% endautoescape %}
<!-- Student doesn't have interview date Modal -->
<div  id="no-interview" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <div class="modal-content">
      <div class="modal-body">
        <h4>
            You can't confirm your interview, because you do NOT have an interview date
        </h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
      </div>
    </div>

  </div>
</div>
{% endblock %}
{% block 'scripts' %}
<script type="text/javascript">
  (function(){
      $.ajax({
        type: "POST",
        url: "{% url 'course_interviews:confirm_student_interview' %}",
        data: {
          'token': '{{ token }}',
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },

        error: function(data){
          $('#no-interview').modal('show');
          $('#no-interview').on('hidden.bs.modal', function () {
              $(location).attr("href", "{% url 'course_interviews:choose_interview' token %} ")
          })
        }

      });
  })();
</script>
{% endblock %}

source/course_interviews/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block 'page-content' %}
{% autoescape off %}
<div class="container">
  <h1>
    Next week will start the second stage of the HackBulgaria's Fall 2015 courses campaign - tech interviews!
  </h1>
  <h3>
    Everyone who had applied will receive an email with information & details about the interviews. 
  </h3>
  <h3>
    <b>So check your email! ;)</b>
  </h3>
  <h3>
    Here are our tips for interviews:
  </h3>
  <ul>
    <li>
    <h4>
      Make sure you’re rested and ready. 
    </h4>
    </li>
    <li>
      <h4>Ensure that your internet connection is stable during the Skype interview</h4>
    </li>
    <li>
      <h4>Check your code - we will ask you questions about your solution's implementation</h4>
    </li>
    <li>
      <h4>Keep calm :)</h4>
    </li>
    <li>
      <h4>Manage well your time</h4>  
    </li>
  </ul>
  <div class="image-container">
    <img src="{% static 'images/quality_education.gif' %}">
  </div>
</div>
{% endautoescape %}
{% endblock %}